### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by petrjac** [redrick/tessera#2]
When run:
```ruby
ticket = Tessera::Ticket.find(441031)
```
I get:
```ruby
/var/lib/gems/2.4.0/gems/tessera-1.0.0/lib/tessera/ticket.rb:20:in `find': undefined method `first' for nil:NilClass (NoMethodError)
	from /srv/www/testboard/jobs/otrs.rb:13:in `<main>'
```

It could be permission problem since I have read-only permission on this ticket...anyway I expected error message from server.

Thank you;)

**Comment by redrick** [comment]
Not able to reproduce, seems like really specific setup of yours, will try to catch you next time, to clarify more what exactly may be happening there...
